const mongoose = require("mongoose");

// A log of "bus arriving soon" alerts, generated by services/notifier.js.
// Kept in the DB (not just pushed over sockets) so the admin dashboard and
// any client that missed the live event can still see recent alerts.
const NotificationSchema = new mongoose.Schema(
  {
    bus: { type: mongoose.Schema.Types.ObjectId, ref: "Bus", required: true },
    route: { type: mongoose.Schema.Types.ObjectId, ref: "Route", required: true },
    stopName: { type: String, required: true },
    message: { type: String, required: true },
    etaMinutes: { type: Number },
  },
  { timestamps: true }
);

module.exports = mongoose.model("Notification", NotificationSchema);
